### ISSUE TITLE
[1.18.2] Combat doesn't lock Entity stats

### ISSUE THREAD

**Issue by MoXAriApph** [Stephen-Seo/TurnBasedMinecraftMod#1]
When going into combat through TBM, your health is not locked in certain situations, if Sand or a block suffocates you, you take damage, this leads to mobs dying when walking towards you in TBM combat getting stuck in terrain.

There are also other issues like you drowning in the middle of combat with mobs like the drowned.

Would suggest entity health is locked (to whatever your health is on that turn) -> make air tick down every turn instead of it being constant, same with Lava ticks if possible.

**Comment by Stephen-Seo** [comment]
@MoXAriApph 

I currently don't have much free time to work on this, but I will probably implement your suggestions soon with options in the server config to disable them (in case someone wants the old behavior).

I don't think this will be too difficult to implement. I think things like preventing drowning would be similar to the code used for preventing movement during battle (which just sets the necessary values on an entity server-side). Preventing suffocation or death-by-lava might be doable if there are forge-event-hooks for them. Otherwise, I may have to get somewhat creative on how to inhibit them during battle.

Thanks for the interest in the mod.

**Comment by Stephen-Seo** [comment]
So I took a quick look at the Forge API since I have a little time right now, and it looks totally doable to prevent lava/drown/suffocation damage during battle. There happens to be two event hooks that trigger when damage is applied to an entity. (Forge events usually can be "cancellable", such that doing so will prevent the thing from happening; in this case, damage.) One of the hooks apply at the start of the damage function, which also provides a "DamageSource" object which can be checked if the source is from lava, suffocation, etc.

So this appears to be totally doable, but I need some time to implement and test it.

**Comment by MoXAriApph** [comment]
Awesome 👍 I'm always down for testing if needed, currently my server is doing a pack overhaul and wanted to include this.

**Comment by Stephen-Seo** [comment]
Feel free to reopen this issue if you think the changes I made doesn't fully address the issue. If you do so, please specifically give the reason why.
