### ISSUE TITLE
I acant make contact with entity

### ISSUE THREAD

**Issue by s4sutler100** [Stephen-Seo/TurnBasedMinecraftMod#2]
I a cant make contact with entity.  Entity is too far or also moving while i am holding still.

**Comment by Stephen-Seo** [comment]
> I a cant make contact with entity. Entity is too far or also moving while i am holding still.

I'm not quite sure what you are saying is happening. Are you saying that the battle gui opens even when far from an enemy? By default, the server config is set to start battle when a mob targets you and is within range. You can change the behavior to only start battle when you are hit by a mob by setting the following in the server-side config:

    [server_config]
    ...
    # If true, only initiate battle on attack. If false, monsters targeting players
    # also trigger battle.
    old_battle_behavior = true
    ...

If you're just playing single-player, then just editing `.minecraft/config/TurnBasedMinecraft/TBM_Config.toml` should be ok. If you're on a server, the server config at `config/TurnBasedMinecraft/TBM_Config.toml` should be edited.

**Comment by s4sutler100** [comment]
yeah its ike behind me and then igives me options i can move and i am getting pummbedtill they burn up in sunlight

**Comment by Stephen-Seo** [comment]
> yeah its ike behind me and then igives me options i can move and i am getting pummbedtill they burn up in sunlight

This mod simulates turn-based combat in the style of RPG games. You take turns deciding what to do; that's what the menu is for. You can choose to attack with your currently held item, you can switch items, you can flee battle, etc. There's a lot of settings you can configure for this as well.

I'm not quite sure if you are seriously asking for help or just trolling. If you don't like the behavior of this mod, then don't use it. You don't have to use this mod if you don't like it. To each their own. If you need help, then state exactly what the problem is so that I or someone else can help you. I cannot help you if you are not stating exactly what the problem is.

**Comment by s4sutler100** [comment]
Why can not the  interaction happen when the enemy is in view not  on the sides or the rear? otherwise your stuck.

**Comment by s4sutler100** [comment]
What ? I am not trolling !   I am simply giving feedback.  I like the mod just don't know how to word my problem.    How can I fight a mob that's attacking me from behind or on my side?   The mob does not stay still or skellys keep attacking while your trying fleeing them.  Meantime zombs are on both sides of you.  I like the idea. but why not have the interaction in your fov or give them a fighting chance.    I think the interaction should take place at 2 blocks in the players fov.

**Comment by s4sutler100** [comment]
I don't understand  why people take feedback as criticism.   This mod has potential.

**Comment by s4sutler100** [comment]
![2023-11-21_12 30 53](https://github.com/Stephen-Seo/TurnBasedMinecraftMod/assets/16606451/6e03a95b-8f8d-4259-a109-e85717db2bf0)
I'm in the castle turret. The giant  is still attacking I can not move even if I flee. 
Same vein skellies see me through the cracks of an abandoned  home. I cant flee even if I hid out of view

**Comment by Stephen-Seo** [comment]
> I'm in the castle turret. The giant is still attacking I can not move even if I flee. Same vein skellies see me through the cracks of an abandoned home. I cant flee even if I hid out of view

You need to change the server config like I already mentioned:

    [server_config]
    ...
    # If true, only initiate battle on attack. If false, monsters targeting players
    # also trigger battle.
    old_battle_behavior = true
    ...

If you set `old_battle_behavior` to `true`, then mobs will cause you to enter battle only if you are directly attacked instead of entering battle by targeting you.

What version of this mod are you using?

**Comment by s4sutler100** [comment]
I was using 1.19.2

**Comment by Stephen-Seo** [comment]
> I was using 1.19.2

There is no version `1.19.2` of the mod, so I assume you're using version `1.21.0` of the mod which works on version `1.19.2` of Minecraft. Like I mentioned earlier, you need to [edit the config](https://github.com/Stephen-Seo/TurnBasedMinecraftMod/blob/972997a49b18baf4924371c9b872eb7e5d7590ea/src/main/resources/assets/com_burnedkirby_turnbasedminecraft/TBM_Config.toml#L29) to change `old_battle_behavior` to `true` so that mobs cannot start battle until they actually hit you. You can use `/tbm-server-edit` to change the config in-game if that's more comfortable for you.

I must also note that version `1.20` of the mod added the ability to ignore some damage sources, so it should prevent mobs like zombies dying in sunlight while in battle.

**Comment by Stephen-Seo** [comment]
I'm going to close this issue due to inactivity. If you feel there is still a problem, feel free to reopen this issue with more information. However, I prefer discussions of this general nature to occur on [curseforge](https://www.curseforge.com/minecraft/mc-mods/turnbasedminecraft/comments) or even email.
